// Generated by gencpp from file robotiq_force_torque_sensor/sensor_accessorRequest.msg
// DO NOT EDIT!


#ifndef ROBOTIQ_FORCE_TORQUE_SENSOR_MESSAGE_SENSOR_ACCESSORREQUEST_H
#define ROBOTIQ_FORCE_TORQUE_SENSOR_MESSAGE_SENSOR_ACCESSORREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotiq_force_torque_sensor
{
template <class ContainerAllocator>
struct sensor_accessorRequest_
{
  typedef sensor_accessorRequest_<ContainerAllocator> Type;

  sensor_accessorRequest_()
    : command()  {
    }
  sensor_accessorRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sensor_accessorRequest_

typedef ::robotiq_force_torque_sensor::sensor_accessorRequest_<std::allocator<void> > sensor_accessorRequest;

typedef boost::shared_ptr< ::robotiq_force_torque_sensor::sensor_accessorRequest > sensor_accessorRequestPtr;
typedef boost::shared_ptr< ::robotiq_force_torque_sensor::sensor_accessorRequest const> sensor_accessorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator1> & lhs, const ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator1> & lhs, const ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotiq_force_torque_sensor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotiq_force_torque_sensor/sensor_accessorRequest";
  }

  static const char* value(const ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
;
  }

  static const char* value(const ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sensor_accessorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotiq_force_torque_sensor::sensor_accessorRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIQ_FORCE_TORQUE_SENSOR_MESSAGE_SENSOR_ACCESSORREQUEST_H
